# Generated by Django 5.1.5 on 2025-01-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_hashtag_post_image_alter_post_content_post_hashtags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
